# Generated by Django 3.2.20 on 2023-10-28 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0082_user_last_confirm_email_request'),
        ('plugins', '0010_auto_20220104_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.EmailField(max_length=254, unique=True)),
                ('stati', models.JSONField(default=dict)),
                ('gruppo_permessi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.group')),
            ],
        ),
    ]
