# Generated by Django 3.2.20 on 2023-10-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountExtra', '0015_alter_userextra_settori'),
        ('plugins', '0011_settore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settore',
        ),
    ]
