# Generated by Django 3.2.20 on 2023-08-19 23:42

from django.db import migrations, models
import django.db.models.deletion
import saleor.plugins.grigoprint.preventivo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodottoPersonalizzato', '0003_auto_20230425_1919'),
        ('checkout', '0059_merge_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventivoLine',
            fields=[
                ('checkout_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='checkout.checkoutline')),
                ('sconto', models.FloatField(default=0)),
                ('personalizzazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preventivo_line', to='prodottoPersonalizzato.prodottopersonalizzato')),
            ],
        ),
        migrations.CreateModel(
            name='Preventivo',
            fields=[
                ('checkout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='checkout.checkout')),
                ('number', models.IntegerField(default=saleor.plugins.grigoprint.preventivo.models.get_numero_preventivo, editable=False, unique=True)),
                ('anno', models.PositiveSmallIntegerField(default=saleor.plugins.grigoprint.preventivo.models.get_anno, editable=False)),
                ('stato_preventivo', models.CharField(choices=[('C', 'Checkout'), ('I', 'Preventivo'), ('A', 'Approvato dal cliente')], default='C', max_length=1)),
                ('precedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successivo', to='preventivo.preventivo')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.AddConstraint(
            model_name='preventivo',
            constraint=models.UniqueConstraint(fields=('number', 'anno'), name='unique_preventivo_number_anno'),
        ),
    ]
