# Generated by Django 3.2.20 on 2023-08-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivo',
            name='stato_preventivo',
        ),
        migrations.AddField(
            model_name='preventivo',
            name='stato',
            field=models.CharField(choices=[('C', 'Checkout'), ('B', 'Bozza, non inviato'), ('I', 'Preventivo'), ('A', 'Approvato dal cliente')], default='C', max_length=1),
        ),
    ]
