# Generated by Django 3.2.20 on 2023-08-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivo', '0003_manual_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivoline',
            name='descrizione_forzata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivoline',
            name='prezzo_netto_forzato',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
