# Generated by Django 3.2.20 on 2023-08-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventivo', '0004_auto_20230821_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventivo',
            options={'ordering': ('-anno', '-number')},
        ),
    ]
