# Generated by Django 3.2.20 on 2023-08-24 18:36

from django.db import migrations, models
import saleor.plugins.grigoprint.preventivo.models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivo', '0005_alter_preventivo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivo',
            name='number',
            field=models.IntegerField(default=saleor.plugins.grigoprint.preventivo.models.get_numero_preventivo, editable=False),
        ),
    ]
