# Generated by Django 3.2.20 on 2023-09-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodottoPersonalizzato', '0003_auto_20230425_1919'),
        ('checkout', '0059_merge_0058'),
        ('preventivo', '0006_alter_preventivo_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventivoLinea',
            fields=[
                ('checkout_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='checkout.checkoutline')),
                ('descrizione_forzata', models.TextField(blank=True, null=True)),
                ('prezzo_netto_forzato', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('sconto', models.FloatField(default=0)),
                ('correlato_su', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correlato_giu', to='preventivo.preventivolinea')),
                ('personalizzazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preventivo_line', to='prodottoPersonalizzato.prodottopersonalizzato')),
            ],
        ),
        migrations.DeleteModel(
            name='PreventivoLine',
        ),
    ]
