# Generated by Django 3.2.16 on 2023-04-24 09:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0179_productvariant_external_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('tipo', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('descrizione', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Particolare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('descrizione', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tessuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('grammi', models.PositiveSmallIntegerField(default=0)),
                ('altezza', models.PositiveSmallIntegerField(default=0)),
                ('fornitore', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TipoStampa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('stampante', models.CharField(blank=True, max_length=256)),
                ('fornitore', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TessutoStampato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocità_stampa', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('velocità_calandra', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
                ('carta_protezione', models.PositiveSmallIntegerField(default=0)),
                ('note', models.TextField()),
                ('tessuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipi_stampa', to='prodottoPersonalizzato.tessuto')),
                ('tipo_stampa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tessuti', to='prodottoPersonalizzato.tipostampa')),
            ],
        ),
        migrations.CreateModel(
            name='ProdottoPersonalizzato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tessuto_stampato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='prodottoPersonalizzato.tessutostampato')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ParticolareMacro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particolari', to='prodottoPersonalizzato.macro')),
                ('particolare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro', to='prodottoPersonalizzato.particolare')),
            ],
        ),
        migrations.CreateModel(
            name='Finitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dati_finitura', models.JSONField()),
                ('finitura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='prodottoPersonalizzato.particolaremacro')),
                ('prodottoPersonalizzato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finiture', to='prodottoPersonalizzato.prodottopersonalizzato')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('prodotto_personalizzato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='prodottoPersonalizzato.prodottopersonalizzato')),
            ],
        ),
        migrations.CreateModel(
            name='DatoParticolare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particolari', to='prodottoPersonalizzato.dato')),
                ('particolare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dati', to='prodottoPersonalizzato.particolare')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tessutostampato',
            constraint=models.UniqueConstraint(fields=('tipo_stampa', 'tessuto'), name='unique_stampa_tessuto_combination'),
        ),
        migrations.AddConstraint(
            model_name='particolaremacro',
            constraint=models.UniqueConstraint(fields=('particolare', 'finitura'), name='unique_particolare_finitura_combination'),
        ),
        migrations.AddConstraint(
            model_name='datoparticolare',
            constraint=models.UniqueConstraint(fields=('particolare', 'dato'), name='unique_particolare_dato_combination'),
        ),
    ]
