# Generated by Django 3.2.16 on 2023-04-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodottoPersonalizzato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tessutostampato',
            old_name='velocità_calandra',
            new_name='velocita_calandra',
        ),
        migrations.RenameField(
            model_name='tessutostampato',
            old_name='velocità_stampa',
            new_name='velocita_stampa',
        ),
    ]
