# Generated by Django 3.2.20 on 2023-10-28 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0186_remove_product_charge_taxes'),
        ('settore', '__first__'),
        ('prodottoPersonalizzato', '0003_auto_20230425_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdottoExtra',
            fields=[
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='product.productvariant')),
                ('is_personalizzabile', models.BooleanField(default=False)),
                ('stati_lavorazione', models.ManyToManyField(to='settore.Settore', verbose_name='Prodotti')),
            ],
        ),
    ]
