# Generated by Django 3.2.16 on 2023-01-31 08:50

from django.db import migrations, models
import django.db.models.deletion
import saleor.account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0075_add_address_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=256, null=True, unique=True)),
                ('valore', models.FloatField()),
                ('info', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Listino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=256, unique=True)),
                ('ricarico', models.FloatField(default=0)),
                ('info', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('user_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='extra', serialize=False, to='account.user')),
                ('denominazione', models.TextField(blank=True, null=True)),
                ('id_danea', models.TextField(blank=True, null=True, unique=True)),
                ('tipo_cliente', models.CharField(choices=[('A', 'Azienda'), ('P', 'Privato'), ('PA', 'Pubblica Amministrazione'), ('R', 'Agenzia Pubblicitaria'), ('D', 'Dipendente')], default='A', max_length=9)),
                ('tel', saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, null=True, region=None)),
                ('cell', saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, null=True, region=None)),
                ('is_rappresentante', models.BooleanField(default=False)),
                ('commissione', models.FloatField(blank=True, default=0)),
                ('piva', models.TextField(blank=True, null=True, unique=True)),
                ('cf', models.TextField(blank=True, null=True, unique=True)),
                ('pec', models.EmailField(blank=True, max_length=254, null=True)),
                ('sdi', models.TextField(blank=True, null=True)),
                ('rif_ammin', models.TextField(blank=True, null=True)),
                ('split_payment', models.BooleanField(default=False, null=True)),
                ('porto', models.CharField(blank=True, choices=[('A', 'Assegnato'), ('F', 'Franco'), ('FAF', 'Franco con addebito in fattura')], default='FAF', max_length=3, null=True)),
                ('vettore', models.CharField(blank=True, choices=[('D', 'Destinatario'), ('M', 'Mittente'), ('V', 'Vettore'), ('VG', 'Vettore GLS'), ('VD', 'Vettore DHL'), ('VB', 'Vettore BRT')], default='VG', max_length=2, null=True)),
                ('pagamento', models.TextField(blank=True, default='Bonifico anticipato', null=True)),
                ('coordinate_bancarie', models.TextField(blank=True, null=True)),
                ('sconto', models.FloatField(blank=True, default=0)),
                ('iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountExtra.iva')),
                ('listino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountExtra.listino')),
                ('rappresentante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to='accountExtra.userextra')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('denominazione', models.CharField(blank=True, max_length=256)),
                ('phone', saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None)),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatti', to='accountExtra.userextra')),
            ],
        ),
    ]
