# Generated by Django 3.2.16 on 2023-01-31 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_add_address_metadata'),
        ('accountExtra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextra',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='userextra',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='account.user'),
            preserve_default=False,
        ),
    ]
