# Generated by Django 3.2.16 on 2023-01-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountExtra', '0002_auto_20230131_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatto',
            old_name='phone',
            new_name='telefono',
        ),
    ]
