# Generated by Django 3.2.16 on 2023-02-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountExtra', '0003_rename_phone_contatto_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatto',
            old_name='utente',
            new_name='userExtra',
        ),
        migrations.AddField(
            model_name='contatto',
            name='uso',
            field=models.CharField(choices=[('A', 'Generico'), ('F', 'Fatturazione'), ('N', 'Notifiche Eccomerce')], default='G', max_length=1),
        ),
    ]
