# Generated by Django 3.2.16 on 2023-02-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_add_address_metadata'),
        ('accountExtra', '0004_auto_20230201_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextra',
            name='is_rappresentante',
        ),
        migrations.AlterField(
            model_name='contatto',
            name='userExtra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatti', to='accountExtra.userextra'),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='rappresentante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to='account.user'),
        ),
    ]
