# Generated by Django 3.2.16 on 2023-02-09 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_add_address_metadata'),
        ('accountExtra', '0006_auto_20230209_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatto',
            name='userExtra',
        ),
        migrations.AddField(
            model_name='contatto',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contatti', to='account.user'),
            preserve_default=False,
        ),
    ]
