# Generated by Django 3.2.16 on 2023-02-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountExtra', '0007_auto_20230209_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatti', to='accountExtra.userextra'),
        ),
        migrations.AlterField(
            model_name='contatto',
            name='uso',
            field=models.CharField(choices=[('G', 'Generico'), ('F', 'Fatturazione'), ('C', 'Consegna'), ('N', 'Notifiche')], default='G', max_length=1),
        ),
    ]
