# Generated by Django 3.2.16 on 2023-02-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountExtra', '0008_auto_20230209_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatto',
            old_name='user',
            new_name='user_extra',
        ),
    ]
