# Generated by Django 3.2.16 on 2023-02-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountExtra', '0009_rename_user_contatto_user_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextra',
            old_name='tipo_cliente',
            new_name='tipo_utente',
        ),
    ]
