# Generated by Django 3.2.16 on 2023-04-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountExtra', '0010_rename_tipo_cliente_userextra_tipo_utente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iva',
            old_name='denominazione',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='listino',
            old_name='denominazione',
            new_name='nome',
        ),
    ]
