# Generated by Django 3.2.20 on 2023-08-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountExtra', '0012_auto_20230803_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='piva',
            field=models.TextField(blank=True, default=None, null=True, unique=True),
        ),
    ]
