# Generated by Django 3.2.20 on 2023-10-28 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0011_settore'),
        ('accountExtra', '0013_alter_userextra_piva'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='settori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plugins.settore'),
        ),
    ]
