# Generated by Django 3.2.20 on 2023-10-28 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settore', '__first__'),
        ('accountExtra', '0014_userextra_settori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='settori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settore.settore'),
        ),
    ]
